<?php
/**
 * @file
 * Module file for servicecontainer_example.
 */

/**
 * @defgroup servicecontainer_example Example: Service container
 * @ingroup examples
 * @{
 * This example demonstrates how use the service container (create and consume services,
 * dependency injection, ...).
 *
 * Examples:
 *
 * - consume service exposed by a static method in \Drupal
 * - consume service exposed by \Drupal->get()
 * - define a new service and consume it
 * - define a new service which depends on other services
 * - define a Controller which implements ContainerInjectionInterface (or extends ControllerBase)
 * - add a compiler pass
 * - define and use a tagged service (simple with TaggedHandlersPass and more complex with manual discovery)
 *
 * @see page_example
 */

/**
 * Implements hook_help().
 *
 * Through hook_help(), a module can make documentation available to the user
 * for the module as a whole or for specific paths. Where the help appears
 * depends on the $path specified.
 *
 * Help text will be displayed in the region designated for help text. Typically
 * this is the 'Help' region which can be found at admin/structure/block.
 *
 * he help text in the first example below, will appear on the simple page at
 * examples/servicecontainer_example/service.
 *
 * The second example text will be available on the admin help page (admin/help)
 * in the list of help topics using the name of the module. To specify help in
 * the admin section combine the path and the module name using '#' as in the
 * example below.
 *
 * @see hook_help()
 */
function servicecontainer_example_help($path, $arg) {
  switch ($path) {
    case 'examples/servicecontainer_example/existing_service':
      // Help text for the simple page registered for this path.
      return t('This is help text for the service page.');

    case 'admin/help#servicecontainer_example':
      // Help text for the admin section, using the module name in the path.
      $output = array(
        '#markup' => t('<p>The Service container example module provides some example about how use the <b>ServiceContainer.</b><br>
                        This component load manage services in our website / webapp. We can create our custom service without think and looking depends.<br>
                        ServiceContainer find for us if exist depends and instance the object of the classes that we have need.<br>
                        The list show some example about some uses of the ServiceContainer:
        </p><p>
        <ol>

        <li>How consume a service exposed by a <b>static method in \Drupal</b>, click <a href="@service_link"> here</a>.</li>
        <li>How consume a service by <b>method service(String $id) </b>, click <a href="@get_service">here</a>.</li>
        <li>How define a <b>new service and consume it</b>, click <a href="@new_service"> here</a> .</li>
        <li>How define a <b>new service with depends and consume it</b>, click <a href="@depends_service"> here</a> .</li>
        </ol>
        </p>

        ',
          array(
            '@service_link' => url('examples/servicecontainer_example/existing_service'),
            '@get_service' => url('examples/servicecontainer_example/existing_service_get'),
            '@new_service' => url('examples/servicecontainer_example/consume_custom_service'),
            '@depends_service' => url('examples/servicecontainer_example/consume_custom_service_with_depends'),

          )
        ),
      );

      return render($output);
  }
}
